package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"net/url"
)
var IP float64


func Anyge(){
  type AutoGenerated struct {
	Name  string `json:"name"`
	Code  string `json:"code"`
	Ccode string `json:"ccode"`
}



anygepip := url.QueryEscape(IP)

	url := fmt.Sprintf("https://any.ge/api/ip/api.php?ip=%s", anygeip)

	
	request, err := http.NewRequest("GET", url, nil)
	if err != nil {
		log.Fatal(err)
		return
	}

client := &http.Client{}
	resp, err := client.Do(request)
	if err != nil {
		log.Fatal(err)
		return
	}

	defer resp.Body.Close()



	// Use json.Decode for reading streams of JSON data
var anyge_response string
  if err := json.NewDecoder(resp.Body).Decode(&anyge_response)
  
		//log.Printe
	

fmt.Println("Name:", anyge_response.Name)
	//fmt.Println("Country   = ", record.CountryName)
//	fmt.Println("Location  = ", record.Location)} 
} 

func main() {
  IP = 8.8.8.8 
  Anyge()
}
